package org.victor.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.victor.model.AbsenceExample;
import org.victor.model.AbsenceKey;

public interface AbsenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    int countByExample(AbsenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    int deleteByExample(AbsenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    @Delete({
        "delete from absence",
        "where student_id = #{studentId,jdbcType=INTEGER}",
          "and date = #{date,jdbcType=DATE}"
    })
    int deleteByPrimaryKey(AbsenceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    @Insert({
        "insert into absence (student_id, date)",
        "values (#{studentId,jdbcType=INTEGER}, #{date,jdbcType=DATE})"
    })
    int insert(AbsenceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    int insertSelective(AbsenceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    List<AbsenceKey> selectByExample(AbsenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AbsenceKey record, @Param("example") AbsenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table absence
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AbsenceKey record, @Param("example") AbsenceExample example);
}