package org.victor.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.victor.model.GradeEvent;
import org.victor.model.GradeEventExample;

public interface GradeEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int countByExample(GradeEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int deleteByExample(GradeEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    @Delete({
        "delete from grade_event",
        "where event_id = #{eventId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    @Insert({
        "insert into grade_event (event_id, date, ",
        "category)",
        "values (#{eventId,jdbcType=INTEGER}, #{date,jdbcType=DATE}, ",
        "#{category,jdbcType=CHAR})"
    })
    int insert(GradeEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int insertSelective(GradeEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    List<GradeEvent> selectByExample(GradeEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "event_id, date, category",
        "from grade_event",
        "where event_id = #{eventId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    GradeEvent selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GradeEvent record, @Param("example") GradeEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GradeEvent record, @Param("example") GradeEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GradeEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    @Update({
        "update grade_event",
        "set date = #{date,jdbcType=DATE},",
          "category = #{category,jdbcType=CHAR}",
        "where event_id = #{eventId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(GradeEvent record);
}