package org.victor.dao;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.victor.model.President;
import org.victor.model.PresidentExample;

public interface PresidentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    int countByExample(PresidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    int deleteByExample(PresidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    @Insert({
        "insert into president (last_name, first_name, ",
        "suffix, city, state, ",
        "birth, death)",
        "values (#{lastName,jdbcType=VARCHAR}, #{firstName,jdbcType=VARCHAR}, ",
        "#{suffix,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, #{state,jdbcType=VARCHAR}, ",
        "#{birth,jdbcType=DATE}, #{death,jdbcType=DATE})"
    })
    int insert(President record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    int insertSelective(President record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    List<President> selectByExample(PresidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") President record, @Param("example") PresidentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") President record, @Param("example") PresidentExample example);
}