package org.victor.model;

import java.util.Date;

public class GradeEvent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_event.event_id
     *
     * @mbggenerated
     */
    private Integer eventId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_event.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column grade_event.category
     *
     * @mbggenerated
     */
    private String category;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    public GradeEvent(Integer eventId, Date date, String category) {
        this.eventId = eventId;
        this.date = date;
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_event
     *
     * @mbggenerated
     */
    public GradeEvent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_event.event_id
     *
     * @return the value of grade_event.event_id
     *
     * @mbggenerated
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_event.event_id
     *
     * @param eventId the value for grade_event.event_id
     *
     * @mbggenerated
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_event.date
     *
     * @return the value of grade_event.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_event.date
     *
     * @param date the value for grade_event.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column grade_event.category
     *
     * @return the value of grade_event.category
     *
     * @mbggenerated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column grade_event.category
     *
     * @param category the value for grade_event.category
     *
     * @mbggenerated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }
}