package org.victor.model;

import java.util.Date;

public class President {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.last_name
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.first_name
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.suffix
     *
     * @mbggenerated
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.birth
     *
     * @mbggenerated
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column president.death
     *
     * @mbggenerated
     */
    private Date death;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    public President(String lastName, String firstName, String suffix, String city, String state, Date birth, Date death) {
        this.lastName = lastName;
        this.firstName = firstName;
        this.suffix = suffix;
        this.city = city;
        this.state = state;
        this.birth = birth;
        this.death = death;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table president
     *
     * @mbggenerated
     */
    public President() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.last_name
     *
     * @return the value of president.last_name
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.last_name
     *
     * @param lastName the value for president.last_name
     *
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.first_name
     *
     * @return the value of president.first_name
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.first_name
     *
     * @param firstName the value for president.first_name
     *
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.suffix
     *
     * @return the value of president.suffix
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.suffix
     *
     * @param suffix the value for president.suffix
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.city
     *
     * @return the value of president.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.city
     *
     * @param city the value for president.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.state
     *
     * @return the value of president.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.state
     *
     * @param state the value for president.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.birth
     *
     * @return the value of president.birth
     *
     * @mbggenerated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.birth
     *
     * @param birth the value for president.birth
     *
     * @mbggenerated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column president.death
     *
     * @return the value of president.death
     *
     * @mbggenerated
     */
    public Date getDeath() {
        return death;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column president.death
     *
     * @param death the value for president.death
     *
     * @mbggenerated
     */
    public void setDeath(Date death) {
        this.death = death;
    }
}